spring:
  application:
    name: products-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=products_cloud
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: 9872

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true
    fetch-registry: true

